// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByplO8DDFCYNQDvUHOxjWFLOeICnD39Gw',
    appId: '1:1010797261506:web:337e142936eec4052f415b',
    messagingSenderId: '1010797261506',
    projectId: 'orderly-f2106',
    authDomain: 'orderly-f2106.firebaseapp.com',
    storageBucket: 'orderly-f2106.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJuuJd02HYKLYQqmJ_rChFzNbualx0hQ',
    appId: '1:1010797261506:android:8c6d017a183e7d192f415b',
    messagingSenderId: '1010797261506',
    projectId: 'orderly-f2106',
    storageBucket: 'orderly-f2106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwTHmYXUW9_62H9J4szA35ZW0Ji8yOkK0',
    appId: '1:1010797261506:ios:1c25e689856c897b2f415b',
    messagingSenderId: '1010797261506',
    projectId: 'orderly-f2106',
    storageBucket: 'orderly-f2106.appspot.com',
    iosBundleId: 'com.example.orderly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwTHmYXUW9_62H9J4szA35ZW0Ji8yOkK0',
    appId: '1:1010797261506:ios:1c25e689856c897b2f415b',
    messagingSenderId: '1010797261506',
    projectId: 'orderly-f2106',
    storageBucket: 'orderly-f2106.appspot.com',
    iosBundleId: 'com.example.orderly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByplO8DDFCYNQDvUHOxjWFLOeICnD39Gw',
    appId: '1:1010797261506:web:45a664c5f680a12a2f415b',
    messagingSenderId: '1010797261506',
    projectId: 'orderly-f2106',
    authDomain: 'orderly-f2106.firebaseapp.com',
    storageBucket: 'orderly-f2106.appspot.com',
  );
}
